var places = ["Machu Picchu", "Grand Canyon", "Ice land", "New Zealand", "Greece"];
console.log(places);
var placesSorted = places.sort();
console.log(placesSorted);
console.log(places);
console.log(placesSorted.reverse());
console.log(places);
console.log(placesSorted);
console.log(placesSorted.reverse());
console.log(places);
